// mnemonicThemes.js
export const mnemonicThemes = {

film: {
    A: "AVATAR",
    B: "BATMAN",
    C: "CASABLANCA",
    D: "DUNKIRK",
    E: "ETERNALS",
    F: "FROZEN",
    G: "GLADIATOR",
    H: "HANCOCK",
    I: "INCEPTION",
    J: "JAWS",
    K: "KINGKONG",
    L: "LOGAN",
    M: "MATRIX",
    N: "NOTEBOOK",
    O: "OCEANS",
    P: "PRESTIGE",
    Q: "QUANTUM",
    R: "ROCKY",
    S: "STARWARS",
    T: "TITANIC",
    U: "UP",
    V: "VERTIGO",
    W: "WALL-E",
    X: "X-MEN",
    Y: "YENTL",
    Z: "ZORRO",
    a: "arrow",
    b: "breakingbad",
    c: "cheers",
    d: "dexter",
    e: "entourage",
    f: "friends",
    g: "got",
    h: "house",
    i: "insecure",
    j: "justified",
    k: "killingeve",
    l: "lost",
    m: "madmen",
    n: "narcos",
    o: "ozark",
    p: "prisonbreak",
    q: "queen",
    r: "rickandmorty",
    s: "strangerthings",
    t: "thecrown",
    u: "umbrellaacademy",
    v: "vikings",
    w: "westworld",
    x: "xfiles",
    y: "you",
    z: "zoo",
},

    
music: {
    A: "ALL-STAR",
    B: "BADGUY",
    C: "CRAZY",
    D: "DESPACITO",
    E: "EYE",
    F: "FAITH",
    G: "GIMME",
    H: "HOLIDAY",
    I: "IMAGINE",
    J: "JUMP",
    K: "KISS",
    L: "LOSE",
    M: "MONEY",
    N: "NUMB",
    O: "ONE",
    P: "PURPLE",
    Q: "QUEEN",
    R: "RESPECT",
    S: "SMOOTH",
    T: "THRILLER",
    U: "UMBRELLA",
    V: "VOGUE",
    W: "WATERFALLS",
    X: "XANADU",
    Y: "YESTERDAY",
    Z: "ZOMBIE",
    a: "adele",
    b: "beatles",
    c: "coldplay",
    d: "drake",
    e: "eminem",
    f: "fleetwoodmac",
    g: "gorillaz",
    h: "halsey",
    i: "imagine",
    j: "jackson",
    k: "kendrick",
    l: "lorde",
    m: "madonna",
    n: "nirvana",
    o: "outkast",
    p: "prince",
    q: "queen",
    r: "rihanna",
    s: "stones",
    t: "taylor",
    u: "usher",
    v: "vampire",
    w: "weeknd",
    x: "xtina",
    y: "york",
    z: "zeppelin",
},

    
geography: {
    A: "ARGENTINA",
    B: "BRAZIL",
    C: "CHINA",
    D: "DENMARK",
    E: "EGYPT",
    F: "FRANCE",
    G: "GERMANY",
    H: "HUNGARY",
    I: "INDIA",
    J: "JAPAN",
    K: "KENYA",
    L: "LEBANON",
    M: "MEXICO",
    N: "NORWAY",
    O: "OMAN",
    P: "POLAND",
    Q: "QATAR",
    R: "RUSSIA",
    S: "SPAIN",
    T: "TURKEY",
    U: "UKRAINE",
    V: "VIETNAM",
    W: "WALES",
    X: "XENOPHOBIA", // No country starts with X, so I used a geography-related term
    Y: "YEMEN",
    Z: "ZAMBIA",
    a: "archipelago",
    b: "bay",
    c: "canyon",
    d: "delta",
    e: "equator",
    f: "forest",
    g: "glacier",
    h: "highland",
    i: "island",
    j: "jungle",
    k: "knoll",
    l: "lagoon",
    m: "mountain",
    n: "narrows",
    o: "ocean",
    p: "prairie",
    q: "quarry",
    r: "river",
    s: "swamp",
    t: "tundra",
    u: "upland",
    v: "valley",
    w: "waterfall",
    x: "xeric", // Means very dry, as in a desert
    y: "yardang", // A type of landform shaped by wind erosion
    z: "zone",
},


sports: {
    A: "ARCHERY",
    B: "BASKETBALL",
    C: "CRICKET",
    D: "DIVING",
    E: "EQUESTRIAN",
    F: "FOOTBALL",
    G: "GOLF",
    H: "HOCKEY",
    I: "ICE_SKATING",
    J: "JUDO",
    K: "KARATE",
    L: "LACROSSE",
    M: "MOUNTAINEERING",
    N: "NETBALL",
    O: "ORIENTEERING",
    P: "PADDLEBOARDING",
    Q: "QUIDDITCH", // A fictional sport from the Harry Potter series
    R: "RUGBY",
    S: "SOCCER",
    T: "TENNIS",
    U: "ULTIMATE_FRISBEE",
    V: "VOLLEYBALL",
    W: "WRESTLING",
    X: "XARE", // A racquet sport from the Basque region
    Y: "YOGA",
    Z: "ZUMBA",
    a: "apparel",
    b: "ball",
    c: "cleats",
    d: "dumbbells",
    e: "equipment",
    f: "frisbee",
    g: "gloves",
    h: "helmet",
    i: "inflator",
    j: "jersey",
    k: "kettlebell",
    l: "leotard",
    m: "mat",
    n: "net",
    o: "outfit",
    p: "paddle",
    q: "quiver", // For holding arrows in archery
    r: "racquet",
    s: "shoes",
    t: "treadmill",
    u: "uniform",
    v: "visor",
    w: "whistle",
    x: "x-trainer", // Short for cross-trainer, a type of exercise machine
    y: "yoga_mat",
    z: "zinc_oxide_tape", // Athletic tape
},

    
animals: {
    A: "ANTELOPE",
    B: "BABOON",
    C: "CHEETAH",
    D: "DOLPHIN",
    E: "ELEPHANT",
    F: "FLAMINGO",
    G: "GIRAFFE",
    H: "HEDGEHOG",
    I: "IGUANA",
    J: "JAGUAR",
    K: "KANGAROO",
    L: "LEMUR",
    M: "MONKEY",
    N: "NUMBAT", // A small marsupial native to Australia
    O: "OCTOPUS",
    P: "PANDA",
    Q: "QUOKKA", // A small marsupial native to Australia
    R: "RHINOCEROS",
    S: "SQUIRREL",
    T: "TURTLE",
    U: "URUTU", // A venomous snake from South America
    V: "VULTURE",
    W: "WALLABY",
    X: "XENOPS", // A small bird from Central and South America
    Y: "YAK",
    Z: "ZEBRA",
    a: "aquarium",
    b: "burrow",
    c: "carnivore",
    d: "den",
    e: "endangered",
    f: "feathers",
    g: "gills",
    h: "habitat",
    i: "incubation",
    j: "jump",
    k: "krill", // A small crustacean eaten by many marine animals
    l: "lair",
    m: "migration",
    n: "nocturnal",
    o: "omnivore",
    p: "predator",
    q: "quills", // Spines on animals like porcupines and hedgehogs
    r: "reptile",
    s: "swarm",
    t: "territory",
    u: "ungulate", // A group of large mammals that includes deer, cattle, and elephants
    v: "venom",
    w: "web",
    x: "xeric", // An adaptation to living in dry environments
    y: "young", // Referring to offspring of animals
    z: "zoology",
},

};
